name: Build Unsigned IPA

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_26.6.app
  SCHEME_NAME: 'EhPanda'

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install iOS 26 Platform
        uses: nick-fields/retry@v4
        with:
          retry_on: error
          max_attempts: 10
          timeout_minutes: 999
          command: xcodebuild -downloadPlatform iOS

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Archive (unsigned)
        run: xcodebuild archive
          -skipMacroValidation
          -scheme ${{ env.SCHEME_NAME }}
          -destination 'generic/platform=iOS'
          -archivePath /tmp/EhPanda.xcarchive
          CODE_SIGN_IDENTITY=
          CODE_SIGN_ENTITLEMENTS=
          CODE_SIGNING_ALLOWED=NO
          CODE_SIGNING_REQUIRED=NO

      - name: Package .ipa
        run: |
          mkdir -p /tmp/Payload
          mv /tmp/EhPanda.xcarchive/Products/Applications/${{ env.SCHEME_NAME }}.app /tmp/Payload/
          sh ./actions-tool/thin-payload.sh /tmp/Payload/${{ env.SCHEME_NAME }}.app
          cd /tmp
          zip -r EhPanda.ipa ./Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: EhPanda-unsigned-ipa
          path: /tmp/EhPanda.ipa
          if-no-files-found: error
